### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by divyenduz** [mittsh/db-s3-backup#8]
Hey, are you still working on this one ?
I tried this with python3 and got a syntax error. 

If you are open to it, I can help you with other issues and python3 migration. Let me know ?

Thanks

**Comment by mittsh** [comment]
Hey @divyenduz to be very honest, no I'm not working on this repo anymore :(
I've written this for Py2.7.x a long time ago, and never seeked to use Python 3 now. I kind of forgot for which project I wrote that, and now we're using AWS RDS which manages all backups nicely, so I don't need this internally anymore.

Though, Py3 support would be lovely. Also, if you'd like to take responsibility for this repo, I'd happily hand it to you :) Just let me know if you're interested…

Clearly also to be more widely used, it needed to be added to `pip` #5

**Comment by divyenduz** [comment]
Hey, yes, I am totally up for it. Albeit, I would love that I get code reviews from you for the things that I plan on doing in this repository. If you want to be totally away from this then I can take full responsibility to maintain this as well :)

Thanks

**Comment by mittsh** [comment]
I don't mind doing code reviews 😄  So I'm totally fine to continue this way if it's fine for you!

**Comment by divyenduz** [comment]
Thanks, this works for me :)

So, the way I would work is I will raise issues on which we can have discussions. Once we have locked on a feature, I will make a PR for review :)

Let's build an awesome project together :+1:

**Comment by mittsh** [comment]
Yeah! Sounds awesome 👍  Thanks a bunch!
